enablePrePostScripts: true

overrides:
  '@eslint/js': '>=10'
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<8.18.0: '>=8.18.0'
  eslint: '>=10'
  '@eslint/eslintrc>ajv': ^6.12.4
  eslint>ajv: ^6.12.4
  minimatch@<10.2.1: '>=10.2.1'
  '@eslint/eslintrc>minimatch': '^3.1.2'
