name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 4'

jobs:
  lint-with-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        fetch-depth: 1

    - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
      name: Install pnpm
      with:
        install: false

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Lint
      run: |
        pnpm lint --fix

    - name: Build
      run: |
        pnpm build
